# Generated by Django 4.2.4 on 2023-08-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_status_alter_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses/', verbose_name='Фото'),
        ),
    ]
