# Generated by Django 4.2.4 on 2023-08-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='image',
            field=models.ImageField(blank=True, upload_to='benefits/', verbose_name='Фото'),
        ),
    ]
