# Generated by Django 4.2.4 on 2023-08-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_image_benefits_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefits',
            old_name='cover',
            new_name='image',
        ),
    ]
