# Generated by Django 4.2.4 on 2023-08-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_cover_benefits_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='image',
            new_name='imag',
        ),
    ]
