# Generated by Django 4.2.4 on 2023-08-22 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_image_courses_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='imag',
            new_name='image',
        ),
    ]
