# Generated by Django 4.2.4 on 2023-08-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_imag_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_start',
            field=models.TimeField(auto_now=True, max_length=255, verbose_name='Старт курса'),
        ),
    ]
