# Generated by Django 4.2.4 on 2023-08-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courses_course_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_start',
            field=models.CharField(max_length=255, verbose_name='Старт курса'),
        ),
    ]
