# Generated by Django 4.2.4 on 2023-08-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_courses_course_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefits',
            name='image',
        ),
    ]
