# Generated by Django 4.2.4 on 2023-08-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_benefits_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('image', models.ImageField(blank=True, upload_to='about/', verbose_name='Фото')),
            ],
        ),
    ]
