# Generated by Django 4.2.4 on 2023-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('course', models.CharField(max_length=255, verbose_name='Курс')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('status', models.BooleanField(default=True, verbose_name='Статус публикации')),
            ],
        ),
    ]
